version: '3'

services:
    nucleus:
        build:
            context: .
            dockerfile: Dockerfile
        image: web-app
        ports:
            - "8080:80"
        volumes:
            - ./dist:/app/dist