version: '3.7'

services:
    nucleus:
        build:
            context: .
            dockerfile: Dockerfile
            target: 'develop-stage'
        image: web-app
        ports:
            # - "8080:80"
            - '8080:8080'
        volumes:
            # - ./dist:/app/dist
            - '.:/app'
        # command: /bin/sh -c "npm rebuild node-sass"
        command: /bin/sh -c "npm i @vue/cli-service && npm rebuild node-sass && npm run serve"
        networks:
            - app-network
networks:
    app-network:
        external: true